/* == ENGINE.HPP =========================================================== **
** ######################################################################### **
** ## Mhatxotic Engine          (c) Mhatxotic Design, All Rights Reserved ## **
** ######################################################################### **
** ## This file is automatically generated by build. Changes are lost     ## **
** ## when the engine is rebuilt.                                         ## **
** ######################################################################### **
** ========================================================================= */
#pragma once                           // Only one incursion allowed
/* ------------------------------------------------------------------------- */
#define VER_NAME    "Mhatxotic Engine"                // Name of engine
#define VER_AUTHOR  "Mhatxotic Design"                // Author of engine
#define VER_MAJOR   24                                // Version major (year)
#define VER_MINOR   11                                // Version minor (month)
#define VER_BUILD   25                                // Version build (day)
#define VER_REV     20                                // Version rev (build#)
#define VER_STR_NQ  24,11,25,20                       // Version as literal
#define VER_STR     "24.11.25.20"                     // Version as string
#define VER_DATE    "Mon Nov 25 19:10:03 2024 +0000"  // Compilation date
/* == EoF =========================================================== EoF == */
