/* == MSENGINE.HPP ========================================================= **
** ######################################################################### **
** ## MS-ENGINE              Copyright (c) MS-Design, All Rights Reserved ## **
** ######################################################################### **
** ## This file is automatically generated by build. Changes are lost     ## **
** ## when the engine is rebuilt.                                         ## **
** ######################################################################### **
** ========================================================================= */
#pragma once                           // Only one incursion allowed
/* ------------------------------------------------------------------------- */
#define VER_NAME    "MS-Engine"                       // Name of engine
#define VER_AUTHOR  "MS-Design"                       // Author of engine
#define VER_MAJOR   24                                // Version major (year)
#define VER_MINOR   11                                // Version minor (month)
#define VER_BUILD   19                                // Version build (day)
#define VER_REV     19                                // Version rev (build#)
#define VER_STR_NQ  24,11,19,19                       // Version as literal
#define VER_STR     "24.11.19.19"                     // Version as string
#define VER_DATE    "Tue Nov 19 23:25:57 2024 +0000"  // Compilation date
/* == EoF =========================================================== EoF == */
