/* == MSENGINE.HPP ========================================================= **
** ######################################################################### **
** ## MS-ENGINE              Copyright (c) MS-Design, All Rights Reserved ## **
** ######################################################################### **
** ## This file is automatically generated by build. Changes are lost     ## **
** ## when the engine is rebuilt.                                         ## **
** ######################################################################### **
** ========================================================================= */
#pragma once                           // Only one incursion allowed
/* ------------------------------------------------------------------------- */
#define VER_NAME    "MS-Engine"                       // Name of engine
#define VER_AUTHOR  "MS-Design"                       // Author of engine
#define VER_MAJOR   24                                // Version major (year)
#define VER_MINOR   9                                 // Version minor (month)
#define VER_BUILD   17                                // Version build (day)
#define VER_REV     1                                 // Version rev (build#)
#define VER_STR_NQ  24,9,17,1                         // Version as literal
#define VER_STR     "24.9.17.1"                       // Version as string
#define VER_DATE    "Tue Sep 17 00:05:28 2024 +0100"  // Compilation date
/* == EoF =========================================================== EoF == */
